# 环境配置
env = "dev" # dev、test、prod、local

# 服务器配置
[server]
name = "moon_palace"

# 元数据
[server.metadata]
description = "palace是moon监控系列的监控平台，用于管理告警、监控、配置、日志、数据源等"
background = "寓意为月宫，表示moon系列的统一管理平台"

# HTTP服务配置
[http]
addr = "0.0.0.0:8000"
timeout = "50s"

# gRPC服务配置
[grpc]
addr = "0.0.0.0:9000"
timeout = "50s"

# JWT配置
[jwt]
sign_key = "moon-sign_key"
issuer = "moon-palace"
expire = "3600s"

# API配置
[api_limit]
allow_list = [
    "/api.admin.authorization.Authorization/Login",
    "/api.admin.authorization.Authorization/Captcha",
    "/api.admin.authorization.Authorization/CreatePassword",
    "/api.Health/Check",
    "/api.Alert/Hook"
]
trusted_list = [
    "/api.admin.authorization.Authorization/Logout",
    "/api.admin.team.Team/MyTeam",
    "/api.admin.authorization.Authorization/RefreshToken"
]
deny_list = []

# 数据库配置
[database]
driver = "mysql"
debug = false
dsn = "root:12345678@tcp(localhost:3306)/moon?charset=utf8mb4&parseTime=True&loc=Local"

# 业务数据库配置
[bizDatabase]
driver = "mysql"
debug = false
dsn = "root:12345678@tcp(localhost:3306)/"

# 告警数据库配置
[alarmDatabase]
driver = "mysql"
debug = false
dsn = "root:12345678@tcp(localhost:3306)/"

[cache]
driver = "free"
# 缓存配置
[cache.redis]
network = "tcp"
addr = "localhost:6379"
db = 0
password = ""
read_timeout = "0.2s"
write_timeout = "0.2s"
dial_timeout = "0.2s"

[cache.nutsDB]
path = "./tmp/nutsdb"
bucket = "test"

[cache.free]
size = 10485760

# 服务发现配置
[discovery]
driver = "etcd"

[discovery.etcd]
endpoints = [
    "localhost:20000",
    "localhost:20002",
    "localhost:20004"
]
username = ""
password = ""
timeout = "50s"

[micro_server]
# 微服务配置
[micro_server.rabbit_server]
network = "rpc"
nodeVersion = ""
endpoint = "discovery:///moon_rabbit"
timeout = "50s"
secret = ""

[micro_server.hou_yi_server]
network = "rpc"
nodeVersion = ""
endpoint = "discovery:///moon_houyi"
timeout = "50s"
secret = ""

#[micro_server.hou_yi_servers]
#[micro_server.hou_yi_servers.0]
#network = "rpc"
#nodeVersion = ""
#endpoint = "discovery:///moon_houyi_1"
#timeout = "50s"
#secret = ""
#
#[micro_server.hou_yi_servers.1]
#network = "rpc"
#nodeVersion = ""
#endpoint = "discovery:///moon_houyi_2"
#timeout = "50s"
#secret = ""


