apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
  namespace: application
  labels:
    app: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
      - name: rabbit
        image: docker.cloudimages.asia/aidemoonio/rabbit:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8002
        - name: grpc
          containerPort: 9002
        volumeMounts:
        - name: rabbit-data
          mountPath: /data/conf/config.yaml
          subPath: config.yaml
      volumes:
      - name: rabbit-data
        configMap:
          name: rabbit-config
