apiVersion: v1
kind: ConfigMap
metadata:
  name: houyi-config
  namespace: application
data:
  config.yaml: |-
    env: dev
    
    dependPalace: true
    server:
      name: moon_houyi
      httpEndpoint: "houyi.application.svc.cluster.local:8001"
      grpcEndpoint: "houyi.application.svc.cluster.local:9001"
      network: "rpc"
      metadata:
        description: 是moon监控系列的告警组件，可以独立部署，接受prom类型规则，也可以接受alertmanager类型组件的告警推送
        background: 寓意为天神后羿，专门用于监控规则告警事件
    http:
      addr: 0.0.0.0:8001
      timeout: 50s
    grpc:
      addr: 0.0.0.0:9001
      timeout: 50s
    
    cache:
      driver: "redis"
      redis:
        network: "tcp"
        addr: redis.middleware.svc.cluster.local:6379
        db: 0
        password: "lQz8OMgje7UyoD"
        read_timeout: 0.2s
        write_timeout: 0.2s
        dial_timeout: 0.2s
    
    watch:
      strategy:
        timeout: 10s
        interval: "@every 10s"
      alertEvent:
        timeout: 10s
        interval: 10s
    
    palace_server:
      network: "rpc"
      nodeVersion: ""
      endpoint: "palace.application.svc.cluster.local:9000"
      timeout: 50s
      secret: ""
