apiVersion: v1
kind: Service
metadata:
  name: houyi
  namespace: application
  labels:
    app: houyi
spec:
  type: ClusterIP
  selector:
    app: houyi
  ports:
  - name: http
    port: 8001
    targetPort: http
  - name: grpc
    port: 9001
    targetPort: grpc

